name: Imports

on:
  schedule:
    - cron: '0 0 * * 1'  # Запускається кожного понеділка о 00:00 UTC
    # - cron: '0 0 * * 5'  # Запускається кожної п’ятниці о 00:00 UTC
  workflow_dispatch:  # Дозволяє запуск вручну

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # або інша потрібна тобі версія

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check installed packages
      run: pip list

    - name: Run import script
      env:
        TOLOKA_USERNAME: ${{ secrets.TOLOKA_USERNAME }}
        TOLOKA_PASSWORD: ${{ secrets.TOLOKA_PASSWORD }}
      run: python runImports.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "btdrbryan@gmail.com"
        git config --global user.name "DrBryanMan"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Автоматичне оновлення JSON" && git push)
